### ISSUE TITLE
Add Ohni (OHNI) by ohni.us

### ISSUE THREAD

**Issue by james8bc** [forkdelta/tokenbase#1278]
**Token address: 0x6f539a9456a5bcb6334a1a41207c3788f5825207**

**Issuer's official website: ohni.us**

**Description: Ohni is the cryptocurrency uniting cryptocurrencies.** 

**A link to the official contract address confirmation: http://www.ohni.us/faq/** 

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://icoholder.com/en/ohni-22390**

**Comment by jamesohni** [comment]
ohni.us
https://bitcointalk.org/index.php?topic=4454146.msg39847860#msg39847860
T.me/OhniGroup
Twitter.com/OhniOfficial
https://discordapp.com/invite/VM7D4R3

**Comment by freeatnet** [comment]
Thank you for your request, @jamesohni! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@jamesohni Needs 2 (two) independent, third-party reviews of the project/token.

**Comment by jamesohni** [comment]
Here is the second review. Thanks.
https://bitcointalk.org/index.php?topic=2101837.0

**Comment by freeatnet** [comment]
@jamesohni icoholder.com has no substance, the bitcointalkthread is not on ohni.us.

**Comment by jamesohni** [comment]
Here is one review:

The Global Moderator of Cryptotalksworld posted this.

https://cryptotalksworld.org/index.php?topic=865.0

I will get the other soon

**Comment by jamesohni** [comment]
A senior member left a review on our Bitcoin talk Ann https://bitcointalk.org/index.php?topic=4454146.msg40180688#msg40180688

**Comment by jamesohni** [comment]
Here are some updates on this situation:

We represent the Ohni.io project. 

The reason we have a new domain is because we fired an employee. They contacted Telegram, Twitter, and our domain registrar to gain access to our accounts (Paul (our COO) or I owned all of these in the first place). Twitter and our domain registrar gave him access to these. Twitter gave us access back after we proved it was us but our domain registrar is now requiring a court order to get the domain back. We are working with our legal team but it could take a year or more to get the domain back. 

Now that we have the Ohni_io Twitter account (it was ours in the first place), we have tweeted on this account about the new address and website. We have the exact same staff members (plus new members) and everything except the domain. The domain DNS records are not authenticated for Ohni.io right now.

Although we have the Ohni_io Twitter account back, we prefer to stay branded as Ohni.us to not cause any more confusion with our community. The previous employee did not even change the mail records so I can still email from admin@ohni.io

@freeatnet requested address verification on or linked from ohni.io and if you scroll to the bottom you can see a Twitter link with the correct address.

Thank you for your time and assistance on this matter,

Best regards,

James
