### ISSUE TITLE
Add ICE ROCK MINING

### ISSUE THREAD

**Issue by miklepluzhnikov** [forkdelta/tokenbase#1298]
Token address: 0xC16b542ff490e01fcc0DC58a60e1EFdc3e357cA6

 Issuer's official website: https://icerockmining.io

Description: Ice Rock’s mining facility is located in a former soviet military bunker. It’s natural constant temperature is 12 celcius, this reduces power costs dramatically as we do not need to cool the facility. Moreover, our power costs are .03 cents per kilowatt hour, a very low cost of energy. We have no mortgage or rent to pay on our facility as it is owned free and clear by Ice Rock’s ceo, Malik Murzashev. These cost savings and other operational efficiencies ultimately result in lower fixed costs which enable us to increase investor ROI. Right now is an exciting time in the mining space, if you are bullish on bitcoin, mining provides you with a generous return and full upside exposure. For those who have considered starting their own mining operation, Ice Rock provides you with similar returns without the operational headache.

A link to the official contract address confirmation: http://ico.icerockmining.io

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2781356.new#new
2. https://portaldobitcoin.com/entrevista-com-ice-rock-mining-mineracao-de-bitcoin-em-bunker-sovietico-abandonado/
3. https://bitnovosti.com/?s=ice+rock&x=14&y=17
4. https://portaldobitcoin.com/ice-rock-mining-mineracao-de-bitcoin-em-um-bunker-secreto-construido-pela-urss/
5. https://bitscreener.com/news/ice-rock-mining-ico-the-future-of-mining

Links:
https://icerockmining.io/
https://twitter.com/icerockmining
https://t.me/icerockmining

**Comment by freeatnet** [comment]
Thank you for your request, @miklepluzhnikov! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by miklepluzhnikov** [comment]
Hello, 

Please give me any updates about listing.

**Comment by freeatnet** [comment]
@miklepluzhnikov I can see an icerockmining.io [ROCK token](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0xdfbd6a960a55bcfcf59d5925351e05a51498bcef.yaml) that was inherited from EtherDelta token list on January 25th; however, it's under a different address and [predates the ICO](https://bitscreener.com/news/ice-rock-mining-ico-the-future-of-mining). Could you elaborate on the situation?

---

Review notes NB:
* "Official" blog (founder's? blog, linked from the website) not updated since before the end of the ICO.
* Claims guaranteed ROI of >300%

Reviews:
1. ~https://bitcointalk.org/index.php?topic=2781356.new#new~ Does not point to any substantial reviews.
2. https://portaldobitcoin.com/entrevista-com-ice-rock-mining-mineracao-de-bitcoin-em-bunker-sovietico-abandonado/ not reviewed yet
3. https://bitnovosti.com/?s=ice+rock&x=14&y=17 yields
    1. ~https://bitnovosti.com/2018/04/02/ico-ice-rock-mining-6-mln/~ press release "as is"
    2. ~https://bitnovosti.com/2018/02/21/vtoraya-faza-ice-rock-mining-nachalo/~ press release
    3. ~https://bitnovosti.com/2018/02/03/ice-rock-mining-privat-pre-ico/~ press release
4. ~https://portaldobitcoin.com/ice-rock-mining-mineracao-de-bitcoin-em-um-bunker-secreto-construido-pela-urss/~ sponsored content (disclaimer at the top)
5. ~https://bitscreener.com/news/ice-rock-mining-ico-the-future-of-mining~ Press release.

Reviews not mentioned in the request:
1. https://medium.com/the-mission/crypto-mining-icos-whitepapers-review-hydrominer-ice-rock-miner-and-envion-d6a50c1ba781
2. https://bitcointalk.org/index.php?topic=2196082.msg22078655#msg22078655 links on companies involved

**Comment by miklepluzhnikov** [comment]
We have just finished the second phase of ICO. 
For the second phase, we issued a new token ROCK2.
