### ISSUE TITLE
stop the order book for SHOP

### ISSUE THREAD

**Issue by doronwesly** [forkdelta/tokenbase#1360]
On behalf of SHOPIN team, we want to request removing of SHOP token in ForkDelta UI and clear order book in Fork Delta. For now the nost critical thing is to halt further trading of SHOP of Forkdelta. 

**What token should be updated?**

We have not commenced with swap yet of new token - we will update you in a couple of days. 

**What about the token should be updated?**

"address": "0xd8ba97571d9a78184bbb599bc41bc10a99ffd72f",
 "msg": "Delete SHOP on ForkDelta UI and clear order book",
 "sig": "0x9c823e0be7581a83114a1c7c6d96629478cbda448e63eda3bc0f61869e08f5d179eb023aa881fe5db4746e019ba2c021dc492c64beec003707bab0f0d38d8fd31c",

**Comment by freeatnet** [comment]
@doronwesly SHOP is not officially recognized by ForkDelta; however, from our previous conversation in chat I understand you mean SHOP with contract address 0x6175f6f85339f1e56affac5a68cbf8297969004d. Can you please confirm that?

**Comment by eraneyal** [comment]
Hi, I’m Eran, CEO at Shopin. Confirming the requested removal.

NPXS = 0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3
NPXS.owner = 0x28744a3ce59a1a2f7fa17e22a3955ba61558356f (message signer)

Message:
Delete NPXS on ForkDelta UI and clear order book #1357

Message signature hash:
0x9a0d39ecdfc5eec7544486feb67db2fa0faef7b2dc5b5ec30ff38feb4b54

Thank you,

Eran

**Comment by freeatnet** [comment]
@eraneyal Err. That appears to be copy-pasted from #1357. Again, here's what needs to happen:
1. Request needs to specify the token address, especially since SHOP is not a recognized token (token symbols are not unique).
2. Request needs to have an identity verification part, consisting of a unique message, signed by the contract owner / creator wallet key. Here's what you can use:

```
I’m Eran, CEO at Shopin. I request that ForkDelta stops the order book for SHOP token (0x6175f6f85339f1e56affac5a68cbf8297969004d) indefinitely due to a hack. This message is signed for the request posted at https://github.com/forkdelta/tokenbase/issues/1360 on June 28, 2018 and cannot be reused after July 5, 2018.
```

The signature must be verifiable via https://etherscan.io/verifySig. The purpose of the signed message is to make sure we're interacting with the owner of the contract directly and that the signature was created for the specific request, and I ask for your understanding in the matter.

**Comment by eraneyal** [comment]
Thanks for the instruction. Here it is redone:

{
  "address": "0xd8ba97571d9a78184bbb599bc41bc10a99ffd72f",
  "msg": "I’m Eran, CEO at Shopin. I request that ForkDelta stop the order book for SHOP token (0x6175f6f85339f1e56affac5a68cbf8297969004d) indefinitely due to a hack. This message is signed for the request posted at https://github.com/forkdelta/tokenbase/issues/1360 on June 28, 2018 and cannot be reused after July 5, 2018.",
  "sig": "0xd06d3047d8de8568aee8cf4c72f7ef1dc9a00377ecd1d6e8d7efc6796d51ced047cc8317c24db478356e0623c6ddd0aa62d1e54a9baac32820d7e6cd0e124bb21c",
  "version": "3",
  "signer": "MEW"
}

**Comment by eraneyal** [comment]
Checked and verified as instructed

**Comment by freeatnet** [comment]
Signature checks out: https://etherscan.io/verifySig/1209

**Comment by freeatnet** [comment]
@eraneyal I've gone ahead and stopped the order book. This means that:
1. No new orders can be placed.
2. Orders are not displayed / transmitted, except to respective order makers, so that they can cancel those orders as needed.
3. Users can withdraw their funds as usual.

Let me know if any other assistance is needed.

**Comment by eraneyal** [comment]
Hi Arseniy,

Thank you for your incredible support and mentor ship through this
difficult process. It’s amazing to know that we all live together in a
strong community that self-polices itself and support one another. We are
here to work with you and support any of your endeavors as well. Thank you
again from the entire team and all its participants.

Best wishes,

[image: photo]
*Eran Eyal*
CEO, Shopin
+1.646.789.1243 | eran@shopin.com | www.shopin.com
<http://us.linkedin.com/in/eraneyal> <http://twitter.com/eraneyal>
<http://medium.com/@eraneyal> <http://shopineverywhere/>
*Winner and best ICO of North America Bitcoin Conference (BTC Miami)*
*Winner and best ICO of CoinAgenda Global 2017*
*Top 5 ICO at Davos d10e*


On Jun 29, 2018 at 5:09 AM, Arseniy Ivanov <notifications@github.com>
wrote:


@eraneyal <https://github.com/eraneyal> I've gone ahead and stopped the
order book. This means that:

   1. No new orders can be placed.
   2. Orders are not displayed / transmitted, except to respective order
   makers, so that they can cancel those orders as needed.
   3. Users can withdraw their funds as usual.

Let me know if any other assistance is needed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/forkdelta/tokenbase/issues/1360#issuecomment-401296739>,
or mute the thread
