### ISSUE TITLE
Add Bionic (BNC)

### ISSUE THREAD

**Issue by bioniccoin** [forkdelta/tokenbase#1504]
Hello team forkdelta 
we want to list our token BIONIC in your services please .

Token address : 
https://etherscan.io/token/0xef51c9377feb29856e61625caf9390bd0b67ea18

Issuer's official website:
https://bionic-coin.io

Description: Bionic created to facilitate the transactions between electronic companies

Address: 0xef51c9377feb29856e61625caf9390bd0b67ea18
Symbol: BNC
Decimals: 8

Bitcointalk : https://bitcointalk.org/index.php?topic=4404010
Website : https://bionic-coin.io
Whitepaper : https://bionic-coin.io/whitepaper.pdf
Email : dev@bionic-coin.io
Github : https://github.com/bioniccoin/BNC
Twitter : https://twitter.com/bionic_coin
Fb : https://www.facebook.com/Bionic-129556584435034/
Telegram : https://t.me/joinchat/FjxGNQ8X2G9OTBMFO1GkkQ
Video Intro : https://www.youtube.com/watch?v=MMMmRwEaufE
Reddit : https://www.reddit.com/user/Bionic_BNC/
Medium : https://medium.com/@bioniccoin

**Comment by freeatnet** [comment]
Thank you for your request, @bioniccoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by bioniccoin** [comment]
thank you we are waiting for any update .

**Comment by bioniccoin** [comment]
we are still waiting for any update

**Comment by bioniccoin** [comment]
BNC token security audit report performed by Callisto Security Audit Department

https://gist.github.com/yuriy77k/2ac131d3ed755ac9179acc55c99dcb93

**Comment by bioniccoin** [comment]
@therealMikkoK

**Comment by therealMikkoK** [comment]
@bioniccoin 
1. Your website mentions Forbes as a media source for your information, Google doesn't know of any articles about you nor any mention of the token in Forbes.com. Please link to the Forbes' site, particularly where your token is mentioned.
2. When looking into your team, your community manager is presented with a picture, followed by gibberish in Latin. Is Latin a commonly used language in your communications?
3. Your website talks of ICO, yet the only way to get token seems to be by buying them from you.
Since your whitepaper doesn't seem to download, I have to assume that you didn't have an ICO at all or if you did it didn't meet it's soft cap. Did you have a successful ICO?
![image](https://user-images.githubusercontent.com/42318985/44303167-51c78780-a342-11e8-92ff-62bc9ef67c8b.png)
with the information presented, I cannot recommend this token to be traded on ForkDelta.
If you feel this decision has been made with inadequate information, or your situation drastically changes this request can be re-opened.

**Comment by bioniccoin** [comment]
@therealMikkoK
