### ISSUE TITLE
URGENT! SCAM ALERT FROM MOBILEGO!

### ISSUE THREAD

**Issue by mobilegoofficial** [forkdelta/tokenbase#2249]
**What token should be updated?**
MGO (0x40395044Ac3c0C57051906dA938B54BD6557F212)

**What about the token should be updated?**
Trading should be stopped

I’m Artur Lee, head of marketing in MobileGo. I ask that ForkDelta stop the order book for MobileGo token 0x40395044Ac3c0C57051906dA938B54BD6557F212 indefinitely due tos strong proofs that current orders has been created by criminals who stolen MGOs from cryptopia exchange. This message is signed for the request posted at onJanuary 29, 2019 and cannot be reused after 1 week from current date in full, eg: February 5, 2019. Please feel free to contact me via official email artur.lee@mobilego.io 
We place our hopes on you. Thank you.

_Updated by @freeatnet: removing erroneous HTML comment markers `<!-- -->`_

**Comment by freeatnet** [comment]
@mobilegoofficial, we need to verify your identity as the owner of the token in order to proceed. Please sign your request using the contract owner wallet (0xed5eca2d2b341ba7eaa93273557f2b56b74f5107) key. You can sign using [MyEtherWallet](https://beta.myetherwallet.com/interface/sign-message) or [MyCrypto](https://mycrypto.com/sign-and-verify-message/sign). Thank you for your understanding.
