### ISSUE TITLE
Momenteum

### ISSUE THREAD

**Issue by momenteum** [forkdelta/tokenbase#326]
Contract address: 0xad6fc7cba45d982e237ed54122ccfc0151eb8f2d

Issuer's official website: http://momenteum.international/

Official contract address confirmation: https://etherscan.io/token/0xad6fc7cba45d982e237ed54122ccfc0151eb8f2d

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2620875.0

Description:

Blockchain: Ethereum

Type: ERC20

Token name: Momenteum

Token abbreviation:MMT

Token decimals: 8

Total supply: 92 000 000

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has no reviews.

**Comment by freeatnet** [comment]
> Momenteum is a public Ethereum-based token for use in mainstream digital wallets, that enables real-time, peer-to-peer value exchange and payment services agnostically across jurisdictions and organizational silos, and across both fiat money and decentralized currencies.
http://momenteum.international ([archived copy](http://archive.is/RX6dX))

> OmiseGO is a public Ethereum-based financial technology for use in mainstream digital wallets, that enables real-time, peer-to-peer value exchange and payment services agnostically across jurisdictions and organizational silos, and across both fiat money and decentralized currencies.
"What is OmiseGO?", https://icobench.com/ico/omisego

But I think the funniest part is that there's a bit in momenteum.international that there's an odd mention of iEthereum:
>  Through the iEthereum _(sic!)_ anyone will be able to conduct financial transactions such as payments, remittances, payroll deposit, B2B commerce, supply-chain finance, loyalty programs, asset management and trading, and other on-demand services, in a completely decentralized and inexpensive way.

Though I first thought it's a typo, iEthereum turns out to be a delightfully similar project, which also ripped off OMG whitepaper ([archived Momenteum WP](http://archive.is/RNQXe), [archived iEthereum WP](http://archive.is/FhUOU)).

@Kryptoniq I can't tell if both projects come from the same author, but we should probably look into IETH.

**Comment by Kryptoniq** [comment]
@freeatnet more details soon.

**Comment by Kryptoniq** [comment]
@freeatnet according to my findings, iEthereum seems to be an abandoned project and the momenteum.international belongs to the people behind iethereum.trade.
Both websites are hosted on the same namecheap.com server.

**Comment by Kryptoniq** [comment]
![img_20180315_235530_388](https://user-images.githubusercontent.com/16838612/37495190-75c99972-28ac-11e8-8c9b-dc482f9339d5.JPG)
![img_20180315_235517_516](https://user-images.githubusercontent.com/16838612/37495196-78d8b90e-28ac-11e8-9763-a997ce43b295.JPG)

**Comment by Kryptoniq** [comment]
Woops! http://momenteum.international has been taken down. Your archive (http://archive.is/RX6dX)  will go a long way.
