### ISSUE TITLE
Listing request BAX token

### ISSUE THREAD

**Issue by leodavinci1** [forkdelta/tokenbase#404]
Contract address: 0x9a0242b7a33dacbe40edb927834f96eb39f8fbcb

Issuer's official website: https://getbabb.com/

Official contract address confirmation: https://getbabb.com/ (it is on the homepage scrolling the page all the way down, its the last thing on the site and says "token address:0x9a0242b7a33dacbe40edb927834f96eb39f8fbcb"

A link to a third-party review or discussion of the token:https://bitcointalk.org/index.php?topic=2349340.0

Description:

**Comment by Kryptoniq** [comment]
There are only 4 token holders ATM.

**Comment by tradedbytony** [comment]
BAX just got unlocked this morning, so only now people are able to withdraw it from their website into their wallets.

It was just announced at https://medium.com/@BABB/bax-tokens-unlocked-fca18f5c7065 less than 5 minutes ago as I'm writing this. In it, the contract address is confirmed by the OP here.

If you go to https://getbabb.com and click on Blog, you'll see that https://medium.com/@BABB is their official blog address.

They are however saying people can leave it on the website too as opposed to withdrawing to their wallets, so the number of token holders might be low for a while (plus it just got announced a few minutes ago so it'll be a while before many people catch on to it).

**Comment by vah13** [comment]
guys, I know that scammers made BABB TOKEN 
https://forkdelta.github.io/#!/trade/0x38c36d3faab64c0770af26cc6ee95d91312bc53c-ETH

it's a *FAKE* address of BABB, please beware 
correct address is 
0x9a0242b7a33dacbe40edb927834f96eb39f8fbcb

**Comment by tradedbytony** [comment]
@vah13 There's fakes of everything. ForkDelta allows anyone with a contract address, symbol and decimals to trade it, though temporarily until they close that tab, to trade it.

For instance, there are almost 20 ONT tokens out there, after it got listed on Binance, however it's a NEO token not an ETH token. The guy that made the fake BERRY token (which hasn't been officially issued yet) also made over a dozen contracts which are trading on EtherDelta/ForkDelta.

Just because something is traded doesn't mean it's real. If it's got the long contract address and not the symbol/ticker shortcut on ForkDelta, then it hasn't been verified by @Kryptoniq or @freeatnet  team and it is a gamble to trade such contracts.

In this case, BAX, the official confirmation of the tokens being released just came in some minutes ago via a blog post.

**Comment by vah13** [comment]
@tradedbytony yea, I know that any contract can use for trade in EtherDelta/ForkDelta.

I just have an idea, you can create some notification for FAKE contracts in your website, and when a legitimate team will found some fake token, they can make a pull request for blocking on your site.

I think it will help for some people.

Tnx

**Comment by Kryptoniq** [comment]
@vah13 your suggestions are welcomed. You can join our Discord channel https://discord.gg/F6Gw9M of you have any contributions to make ForkDelta more better. Thank you.

**Comment by vah13** [comment]
@Kryptoniq tnx, I will write it on the channel.

**Comment by tradedbytony** [comment]
@freeatnet now that they have officially started to send out the tokens (https://medium.com/@BABB/bax-tokens-unlocked-fca18f5c7065) and the contract has been verified by that official post as https://etherscan.io/token/0x9a0242b7a33dacbe40edb927834f96eb39f8fbcb do we still need to add anything else here or is it clear to be listed now?

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9a0242b7a33dacbe40edb927834f96eb39f8fbcb, https://getbabb.com/

**Comment by freeatnet** [comment]
@leodavinci1 Thank you for your request! BAX has been listed: https://forkdelta.github.io/#!/trade/BAX-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
