### ISSUE TITLE
Requesting re-vetting of Black Garlic (BGL)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#463]
I believe Black Garlic (BGL) token requires a review. The project consists of a single web page and a BitcoinTalk announcement with no public discussion. Extensive search for other information sources is unsuccessful.

**Comment by tradedbytony** [comment]
"Contact Us" only links to "About Us" on their website.

They list 3 exchanges on their website, but instead of listing ForkDelta they list EtherDelta which doesn't have the ticker for them (BGL) like ForkDelta has.

They have YoBit and CoinExchange listed on their website as active exchanges trading their tokens but BGL is nowhere to be found in them. They list Token Store in their bitcointalk thread as another possible exchange, and yet again they're nowhere to be found in that exchange.

Their Twitter account has only 7 tweets.

This token has 28 token holders with 38 txs total. ALL token holders have nothing else in their wallets other than BGL tokens.
