### ISSUE TITLE
LiveEdu(ledu)

### ISSUE THREAD

**Issue by newskymoon** [forkdelta/tokenbase#487]
Contract address:0xb1f50b0404da1be06718e3233fb8b1bc192f82d5

Issuer's official website:http://www.liveedu.tv

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:LiveEdu is a project learning platform where content creators teach learners how to build real products. Use practical projects to learn how to build products from the fields programming, game development, data analytics, design, augmented reality, virtual reality, artificial intelligence and cryptocurrencies. Our content is available either as live stream, archived video or uploaded video. We are a distributed company with legal office in San Francisco. We are the world's largest project learning platform.

**Comment by tradedbytony** [comment]
Good try, but no.

First, that's not the real contract. The real contract can be found at https://tokensale.liveedu.tv/en/faq/faq-questions and it's 0x5b26c5d0772e5bbac8b3182ae9a13f9bb2d03765, rather than one with 3 token holders.

Also, the real EDU has already been listed (#306).

Plus, you know we can see all the bunch of other different contracts you've made trying to rip off other tokens right?

**Comment by freeatnet** [comment]
You tell 'em, @tradedbytony!
