### ISSUE TITLE
Formalize Listing Procedure

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#495]
This change/proposal was brought about because we needed a more thorough listing procedure that the ForkDelta team can follow on every single token submission.

Benefits:
This decreases the likelihood that we will list malicious tokens.
This increases the openness of our procedure and opens it up for community feedback.
This formalizes a procedure, so people understand the process for getting listed.

----

### Formats We Accept

- Pull Requests
- Issues

## Order That We Process Listings In

We utilize a priority system to determine the order in which we process listings that goes in this order, from 1 to 6.

1. High Priority - Pull Request
2. Medium Priority - Pull Request
3. Low Priority - Pull Request
4. High Priority - Issue
5. Medium Priority - Issue
6. Low Priority - Issue

If multiple requests fall into one category, they will be processed in the order they were received.

## Priority System Explained

Tokens will be assigned a priority according to the following criterias. The token only has to match one criteria to fall into a higher category, not all.

**High Priority**
- greater than or equal to 3,000 token holders
- greater than or equal to $15,000,000 raised / total market cap

**Medium Priority**
- greater than or equal to 500 token holders
- greater than or equal to $1,000,000 raised / total market cap
- Coinmarketcap listing

**Low Priority**
- Everything else falls in this category

## Listing Procedure For ForkDelta

1. A ForkDelta team member will make sure that the listing contains all of the information outlined above.

    1a) If the listing is missing information, the issue will be marked `missing information`. The team member will also comment on the issue explaining what information is missing. If an issue has been marked `missing information` for 10 days and there has been no response from the token team, the issue will be closed.

2. Then, several procedures must be followed to verify the validity of this submission:

    - Thorough Google search using the requested name and ticker. Is this project claiming to be something it is not? Is the website linked a duplicate of the original?
    - Look at the contract creator address in Etherscan. Are they associated with any other confirmed scams? Is there suspicious activity originating from their address?
    - Make sure the token has proper ERC20 or ERC223 support.
    - Look for any plagiarization including, but not limited to: pictures, names, descriptions. If plagiarization is found, listing request will be denied.
    - Look for misrepresentations present in token issuer's website or marketing material. This includes falsified links, false company partnerships, etc.
    - Look for fake team member information.
    - Look for fake physical addresses.
    - Triple check that the given website / whitepaper / etc. links are official. Utilize Google and social media to search for the specific project and go to the official links. 

3. Once the validity of the submission has been verified, the submitted contract address must be verified on official material.

4. Once the validity is confirmed and the address is verified, the ForkDelta team member should label the issue `information complete`.

5. Then, the team member should leave this in the comments:
> Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

6. The team member should also leave the token address and website in the comment in the following format:
> 0x00000000000000000000000000000,https://ethereum.org

7. After the issue is marked as complete, either @freeatnet or @JonathonDunford will look through the issue as soon as they have time. They will do __1__, ___2___, and __3__ so that we have another set of eyes fully verifying the token.

8. If the token passes these checks, it will be included in a token listing pull request to https://github.com/forkdelta/tokenbase/

9. That pull request must be reviewed and verified by at least one other source.

10. When that pull request is accepted, it will be merged into tokenbase.

11. When the pull request is merged into tokenbase, @freeatnet or @JonathonDunford will run the necessary scripts to add it into https://github.com/forkdelta/forkdelta.github.io

12. They will then create another pull request to https://github.com/forkdelta/forkdelta.github.io that will require a second review of its contents.

13. Once that pull request is reviewed, verified, and accepted, it can be merged into the `master` branch on https://github.com/forkdelta/forkdelta.github.io

#### Tools To Help

https://icocheck.io/
https://www.clearify.io/

**Comment by tradedbytony** [comment]
If I may add, would it be possible to request for the token wanting to be listed to have their own website rather than a free website? For instance, there are some tokens such as https://forkdelta.github.io/#!/trade/EM-ETH (not to mention, that token doesn't even have properly set up links there and use the default Wix ones) which don't even own their own site. If they can't even afford to spend a few bucks for their own domains, perhaps they aren't worth listing. That's just my humble opinion.

**Comment by JonathonDunford** [comment]
I am going to copy our comments over here: https://github.com/forkdelta/tokenbase/issues/473

Original issue has been separated into two and I think our previous comments are important for the other issue. Further discussion token listing requirements should take place there. This will be for our listing procedure.

**Comment by tradedbytony** [comment]
Considering many of these tokens manage to raise millions of dollars, having their own website shouldn't be an issue. Even small ICOs that raise a few hundred dollars have their own site.

In the case of FD, running off GH is actually a good thing because it shows the open resourcefulness of the project. In the case of a token/coin, having their own site shows commitment to the project not to mention the investors would want to check out the WHOIS and make sure the people behind it are transparent or not with that information.

Social media presence should be required, I believe. Shows the team is active and proactively engaging with their audience. Emails can take a long time to respond to. At the very least have a Twitter account. Telegram would be nice too. Having a blog in Medium would be ideal to push updates.

I've seen tokens, even tokens listed here on FD, with no email/twitter/TG/smoke signals or any kind of way to get in touch with the people behind it. I think the tokens with zero-interaction shouldn't even be considered. In the case of the example I listed earlier, that EM token, besides not having their own site they didn't even take the time to edit the default Wix template for social media and those social media links in there link to the default Wix ones.

**Comment by tradedbytony** [comment]
Also, if I'm getting #473 right, there's going to have a change to the template for when we open a new issue. For instance, right now when we open an issue it shows "A link to a third-party review **or** discussion of the token" which makes us choose between a third-party review OR bitcointalk, while #473 suggest we'll need BOTH. Therefore, I suggest changing the default template to indicate this change.

**Comment by JonathonDunford** [comment]
@tradedbytony Can you move these comments over to #473 ?

**Comment by tradedbytony** [comment]
@JonathonDunford will do.

**Comment by JonathonDunford** [comment]
I just realized we should have a priority system as well. Some of these listings are MUCH lower priority than others and it's clear that the first come, first serve method isn't the best.

Maybe a high, low, medium labeling system.

**Comment by Kryptoniq** [comment]
Oops, I'm sorry, i Mistakenly tapped the "close button.

**Comment by Kryptoniq** [comment]
Tokens that have minting functions should explain its  importance to the project. The token's team members can easily mint and dump tokens on the exchange, thus causing inflation and also, affecting the early genuine investors.

**Comment by freeatnet** [comment]
1. Listing requester may not always be the token team (@tradedbytony 😏). I think we should encourage that, is there anything in this workflow that may be an issue when a requester isn't the token team?
2. If the requester would like to add or update information in the request, they should do so in the original issue. An issue closed due to incomplete information may be re-opened by the requester at any time, creating a new issue is not necessary.
3. Should the listing be denied, an "invalid" tag will be assigned to the issue. The requester may appeal that decision in the same issue by clearly and concisely stating reasons we should re-evaluate the listing.
4. The token listings team receives notifications on relevant issues. Personal at-mentions are not necessary unless the requester wants attention of a specific tokens team member. `@forkdelta/token-team` can be used if the request requires immediate attention or if there has been no response from the team for 10 days.
5. I'd like to move to a "one token = one PR" system, not sure if we should specify this here. We may want some additional tooling for that, but that gives us the benefit of easily stopping a single listing if we find an issue later on in the cycle.

Looks good otherwise though!

NTS: We might be able to automate some of this with https://github.com/probot/probot and https://github.com/apps/stale

**Comment by freeatnet** [comment]
One more thought: the tokenbase team member should archive (e.g., via archive.is) materials used to make a decision, at the very least the website and any important public discussion pages.

**Comment by tradedbytony** [comment]
Having a list of importance for listing would be great. As Jonathon said, going from high to medium to low would allow you guys to prioritize the ICOs that brought in 20-50mil first. A token with 2000-10000 token holders should have a higher priority to be listed than one with 30-80 tokens.

A system like this would also mean that even though someone requested their tokens to be listed first they might not necessarily be listed, or even receive the "information complete" label before someone else who made a request after they did. The question is, would that piss people off? Would it even matter if that means we'd get the big tokens in first? Should tokens with 2000-10000 token holders take precedence over the 80-200 token holders?

**Comment by freeatnet** [comment]
@tradedbytony @JonathonDunford My favourite question: why do we need a priority system? :)

**Comment by freeatnet** [comment]
One more thing: I've applied a cooldown period to #433 at my own discretion; however, we should codify that requesting listing is a privilege, and it can be temporarily revoked in certain cases where the requester would otherwise hogging attention without substantial improvement in the quality of the request.

**Comment by tradedbytony** [comment]
@freeatnet A priority system would allow you guys to list the more important tokens, or token contract changes, first. Right now you guys are spending a lot of time going through many tokens making sure all is okay and vetting them by first come first serve basis. A priority system would allow us to not have to vet the smaller projects right off the bat. No longer going through the process of vetting one by one as they are listed, but rather going to be spending time vetting the ones which have the potential to bring high trade and visibility to ForkDelta first. This wouldn't mean abandoning smaller projects, they'd get in too, just not before a huge project.

**Comment by freeatnet** [comment]
@tradedbytony It sounds like the idea is to list high-impact tokens first. However, using a 7-day turnaround time as the low bar, I'm not sure if it's necessary or possible to prioritize the token listings.

Is our concern with requests for important tokens getting stuck in the pipeline because of missing required info? In that case, I'd suggest an informal approach: if the reviewer deems the token to be high-impact and/or otherwise beneficial to the exchange, they may assist in getting it listed first, including adding missing required details.

**Comment by JonathonDunford** [comment]
@freeatnet 

There are plenty of strategic benefits for us as well as benefits for the crypto community if we adopt a priority system currently.

**Strategic Benefits for ForkDelta**
- Increased user volume
- We can be first to list prominent projects. If the exchange is somewhat sizable, users tend to stay with the first exchange that listed the token.
- Possibly increased exposure in terms of announcements by project developers

**Benefits for Community**
- We provide security by officially listing these tokens. We all know how many scams go on when tokens aren't officially listed and people link random contract addresses everywhere.
- We provide a platform for the community to trade their token on

Yes, if we had an incredibly quick turnaround time for token listings, this wouldn't be an issue and in an ideal world, that would be the case. However, in reality, we are not there yet and as such need a system in place in the mean time. We do not have a full time team on token listings and, as such, there are issues that have been open for weeks.

This would help us strategically get the more prominent projects out first and would present a better use of our currently limited time. It would directly increase user growth and volume on the exchange while simultaneously helping more people.

**Comment by JonathonDunford** [comment]
Rough draft of my proposed priority system (added to original issue coment as well)

## Order That We Process Listings In

We utilize a priority system to determine the order in which we process listings that goes in this order, from 1 to 6.

1. High Priority - Pull Request
2. Medium Priority - Pull Request
3. Low Priority - Pull Request
4. High Priority - Issue
5. Medium Priority - Issue
6. Low Priority - Issue

If multiple requests fall into one category, they will be processed in the order they were received.

## Priority System Explained

Tokens will be assigned a priority according to the following criterias. The token only has to match one criteria to fall into a higher category, not all.

**High Priority**
- greater than or equal to 3,000 token holders
- greater than or equal to $15,000,000 raised / total market cap

**Medium Priority**
- greater than or equal to 500 token holders
- greater than or equal to $1,000,000 raised / total market cap

**Low Priority**
- Everything else falls in this category

**Comment by freeatnet** [comment]
Link to approved ("information complete") requests, least recently updated (so oldest approved) first: https://github.com/forkdelta/tokenbase/issues?q=is%3Aopen+label%3A%22information+complete%22+sort%3Aupdated-asc
