### ISSUE TITLE
Ohni Update

### ISSUE THREAD

**Issue by jamesohni** [forkdelta/tokenbase#636]
We are requesting the Ohni address be updated. Our previous CEO is no longer with us however has the old contract access so we merged contracts. 

We are the proper owners and have the trademark for Ohni.

**Comment by JonathonDunford** [comment]
Note: I received an email from admin@ohni.io & james@ohni.us confirming this request.

**Comment by JonathonDunford** [comment]
0x6f539a9456a5bcb6334a1a41207c3788f5825207

Address verified in update.pdf
Verified update.pdf link in pinned message by admin in Ohni telegram
New address also showing up in MEW

The trademark doesn't verify anything pertaining to this issue other than Pauls Bertulis filed the trademark for their logo.

Their telegram is linked directly on the .io website and reflects the new website and address.

**My summary on this issue:**

This was a hostile takeover of Ohni from the majority of their development team to oust the former CEO. James here is the new CEO. The official website doesn't reflect this change because the old CEO has access to the website, however several forms of their social media reflect this including Telegram and Bitcointalk. From what I have seen in the chats, the community seems to agree with this update and there hasn't been any update from the other CEO.

I am going to say that this change is OK in my book.

**Comment by JonathonDunford** [comment]
@jamesohni 

Please read and comment on : https://github.com/forkdelta/tokenbase/pull/658

**Comment by freeatnet** [comment]
https://twitter.com/ohni_io/status/974593090697728001

@jamesohni If you would like to list your token, please file a listing request as a separate project.
